version: "3.9"

services:
  mongo:
    image: mongo:8.0.13
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
        - microservices-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - microservices-network

  discovery-service:
    image: discovery-service:1.0
    container_name: discovery-service
    build: ./ServiceRegistry
    ports:
      - "8761:8761"
    networks:
        - microservices-network

  user-service:
    image: user-service:1.0
    container_name: user-service
    build: ./userservice
#    ports:
#      - "8081:8081"
#    expose:
#      - "8081"
    networks:
        - microservices-network
    depends_on:
      - mongo
      - discovery-service

  rating-service:
    image: rating-service:1.0
    container_name: rating-service
    build: ./ratingservice
#    ports:
#      - "8083:8083"
    networks:
        - microservices-network
    depends_on:
      - mongo
      - discovery-service

  api-gateway:
    image: api-gateway:1.0
#    container_name: api-gateway
    build: ./apiGatewayService
#    ports:
#      - "8084:8084"
    networks:
        - microservices-network
    depends_on:
      - discovery-service

  hotel-service:
    image: hotel-service:1.0
    container_name: hotel-service
    build: ./hotelservice
#    ports:
#      - "8082:8082"
    networks:
        - microservices-network
    depends_on:
      - mongo
      - discovery-service
volumes:
  mongo-data:
    driver: local

networks:
    microservices-network:
        external: true
        name: microservices-network

