spring.application.name=HOTEL-SERVICE
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/mydb?authSource=admin
spring.data.mongodb.database=mydb
spring.depends=mongo

server.port=8082

eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss:SS} - [%t] [%level] [%X{sessionId}] %logger{36}[%L] - %msg%n

management.endpoints.web.exposure.include=health,info
