version: "3.9"

services:
  discovery-service:
    image: iamamithari/discovery-service:1.0
    container_name: discovery-service
    build: ./ServiceRegistry
    ports:
      - "8761:8761"
    networks:
      - microservices-network


networks:
    microservices-network:
        external: true
        name: microservices-network