server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      #uri: mongodb+srv://hari:jDJXY7UiAX5OqW3B@mongodb.y5ywqil.mongodb.net
      uri: mongodb://root:password@mongo:27017/mydb?authSource=admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
